[[headers]]
for = "/api/*"
    [headers.values]
        User-Agent = "212;v1;1.170.29;3;1"

[[redirects]]
from = "/api/*"
to = "https://api.cotrapi.workers.dev/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
