/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHome: typeof import('./components/AppHome.vue')['default']
    RankingGuild: typeof import('./components/RankingGuild.vue')['default']
    RankingPlayerLevel: typeof import('./components/RankingPlayerLevel.vue')['default']
    RankingPlayerPowerGems: typeof import('./components/RankingPlayerPowerGems.vue')['default']
    RankingPlayerRich: typeof import('./components/RankingPlayerRich.vue')['default']
    RankingPlayerSkin: typeof import('./components/RankingPlayerSkin.vue')['default']
    RankingPlayerSurvival: typeof import('./components/RankingPlayerSurvival.vue')['default']
    RankingPlayerTrophy: typeof import('./components/RankingPlayerTrophy.vue')['default']
    RankingRich: typeof import('./components/RankingRich.vue')['default']
    RankingStyle: typeof import('./components/RankingStyle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
